version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase
      - npm install
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - npm run build:prod
      - echo Entered the build phase...
  post_build:
    commands:
      - echo Entered the post_build phase...
      - aws s3 sync dist s3://pipetest1
artifacts:
  files:
    - 'dist/**/*'
  discard-paths: yes